site_name: pypelay
theme:
  logo: pyseas-logo.svg
  name: material
  features:
    # navigation.tabs
    # navigation.sections
    # navigation.top
    # navigation.expand
    # toc.integrate
  palette:
    - scheme: default
      toggle: 
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle: 
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: lime
nav:
  - Introduction: index.md
  - Installation: installation.md
  - User guide: user_guide.md
  - Examples: examples.md
  - Spreadsheets: spreadsheets.md
  - Reference: reference.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          show_source: false
          show_root_heading: true
          docstring_section_style: table
          heading_level: 2
